[tool.poetry]
name = "pd2wasm"
version = "1.0.1"
description = "pd2wasm convert a PureData patch to Wasm file."
authors = ["Charles K. Neimog <charlesneimog@outlook.com>"]
license = "MIT"

[build-system]
build-backend = "poetry.core.masonry.api"

