name: Python Wheels
on:
  workflow_dispatch:
  push:
    branches: ["main", "v2.0.0"]
  pull_request:
    branches: ["main", "v2.0.0"]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install google
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install chromium-chromedriver
      - name: Install pd4web
        run: |
          pip install poetry selenium flask
          poetry build
          pip install dist/*.whl
      - name: Tests
        run: |
          python3 ./Tests/Tests.py
      - name: Upload Wheels
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: pd4web-2.0.0-py3-none-any.whl
          path: dist/pd4web-2.0.0-py3-none-any.whl
