name: pd4web Tests
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:  
  # ==============================================================================
  # =                               WINDOWS                                      =
  # ==============================================================================
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pd4web
        run: |
          pip install poetry selenium
          poetry build && poetry install
          $wheels = Get-ChildItem -Path dist\*.whl
          pip install $wheels

      - name: Tests
        run: |
          cd pd4web/tests/
          python ./runTests.py

      - name: Upload Compiled website
        uses: actions/upload-artifact@v2
        with:
          name: compiledWebsite
          path: pd4web/tests/


  # ==============================================================================
  # =                               MAC INTEL                                    =
  # ==============================================================================
  
  macos-intel-build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pd4web
        run: |  
          pip install poetry certifi selenium
          CERT_PATH=$(python -m certifi)
          export SSL_CERT_FILE=${CERT_PATH}
          export REQUESTS_CA_BUNDLE=${CERT_PATH}
          poetry build
          pip install dist/*.whl

      - name: Tests
        run: |
          cd pd4web/tests/
          python3 ./runTests.py
      
# ==============================================================================
# =                               LINUX                                        =
# ==============================================================================

  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pd4web
        run: |
          pip install poetry selenium
          poetry build 
          pip install dist/*.whl

      - name: Test pd4web
        run: |
          pd4web --help

      - name: Tests
        run: |
          cd pd4web/tests/
          python3 ./runTests.py

  trigger-only-if-all-passed:
    needs: [windows-build, macos-intel-build, linux-test] # List all previous jobs here
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Only If All Passed
        run: echo "All previous jobs have passed."
