---
name: Publish
on:
  workflow_dispatch:
  push:
    tags: '*'
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install linux requirements
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install chromium-chromedriver
          pip install selenium flask
      - name: Install pd4web
        run: |
          pip install .
      - name: Tests
        run: |-
          python3 ./Tests/Tests.py
  publish:
    runs-on: ubuntu-latest
    needs: tests
    strategy:
      matrix:
        python-version: ['3.11']  # just need one version (py3-none)
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pd4web
        run: |
          pip install poetry
          poetry build
          pip install dist/*.whl
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
