---
name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags: '*'
jobs:
  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']  # just need one version (py3-none)
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pd4web
        run: |
          pip install poetry
          poetry build
          pip install dist/*.whl
      - if: github.event_name == 'release'
        name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
